### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by vlkpa** [NativeVision/viro#143]
The error from the firebase crashlytics dashboard:
```
com.viromedia.bridge.module.MaterialManager.<clinit>

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/base.apk", zip file "/data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.en.apk", zip file "/data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.x86.apk", zip file "/data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/lib/x86, /data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/base.apk!/lib/x86, /data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.en.apk!/lib/x86, /data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.x86.apk!/lib/x86, /data/app/com.tut.mobile.android-UL4yBoHZcr63Y5myZhqaqw==/split_config.xxhdpi.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libviro_renderer.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
       at java.lang.System.loadLibrary(System.java:1669)
       at com.viromedia.bridge.module.MaterialManager.<clinit>(MaterialManager.java:58)
       at com.viromedia.bridge.ReactViroPackage.createNativeModules(ReactViroPackage.java:111)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
       at java.lang.Thread.run(Thread.java:764)
```
Viro version:
"@viro-community/react-viro": "2.22.0",

**Device:**
Version: Android 9
Orientation: Portrait
Rooted: Yes
Model: GCE x86 phone
Orientation: Portrait
RAM free: 6.13 GB
Disk free: 2.75 GB

**And Device:** 
Brand: OnePlus
Model: OnePlus8Pro
Orientation: Portrait
RAM free: 1.97 GB
Disk free: 2.97 GB
Version: Android 11
Orientation: Portrait
Rooted: Yes

**Comment by nguyen95** [comment]
I think GCE x86 phone is google auto test device. My app crash on this device only and not in other
